# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               
tagline:             
url:                 artofkot.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Artem Kotelskiy
  url:               https://twitter.com/artofkot
  email:             artofkot@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/artofkot/artofkot.github.io

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'